config/routes.rb
Rails.application.routes.draw do
  resources :metals
  resources :estimates, only: [:index, :show, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "estimates#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dxf_estimator.rb
require 'base64'
require 'pycall'

class DxfEstimator
  UNITS = {
    0 => '(?)',
    1 => 'in',
    2 => 'ft',
    3 => 'mi',
    4 => 'mm',
    5 => 'cm',
    6 => 'm',
  }

  attr_reader :content

  class DefaultEntity
    attr_reader :entity

    def initialize(entity:)
      @entity = entity
    end

    def length
      0
    end
  end

  class LineEntity
    attr_reader :entity

    def initialize(entity:)
      @entity = entity
    end

    def length
      Math.sqrt(
        (entity.dxf.start[0] - entity.dxf.end[0]) ** 2 +
        (entity.dxf.start[1] - entity.dxf.end[1]) ** 2
      )
    end
  end

  class ArcEntity
    attr_reader :entity

    def initialize(entity:)
      @entity = entity
    end

    def length
      (
        ((entity.dxf.end_angle - entity.dxf.start_angle) * Math::PI / 180) *
        entity.dxf.radius
      ).abs
    end
  end

  def self.resolve(type)
    {
      'LINE' => LineEntity,
      'ARC' => ArcEntity,
    }.fetch(type, DefaultEntity)
  end

  def initialize(content:)
    @content = content
  end

  def ezdxf
    @ezdxf ||= PyCall.import_module("ezdxf")
  end

  def bbox
    @bbox ||= PyCall.import_module("ezdxf.bbox")
  end

  def encoded_content
    @encoded_content ||= Base64.encode64(content)
  end

  def drawing
    @drawing ||= ezdxf.decode_base64(encoded_content)
  end

  def entities
    @entities ||= PyCall::IterableWrapper.new(drawing.modelspace).map { |entity| self.class.resolve(entity.dxftype).new(entity: entity) }
  end

  def length
    entities.sum(&:length)
  end

  def bounding_box
    @bounding_box ||= bbox.extents(drawing.modelspace)
  end

  def width
    bounding_box.extmax[0] - bounding_box.extmin[0]
  end

  def height
    bounding_box.extmax[1] - bounding_box.extmin[1]
  end

  def units
    UNITS.fetch(drawing.units, '(?)')
  end
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :metal, inverse_of: :estimates

  validates :name, :file, :length, :width, :height, :units, presence: true

  def cut_price
    Money.new(cut_time * configuration[:cut_price_cents], configuration[:cut_price_currency])
  end

  def cut_time
    (configuration[:cut_speed] * length).seconds
  end

  def metal_price
    metal.price * width * height
  end

  def total_price
    cut_price + metal_price
  end

  def configuration
    Rails.application.config_for(:estimates)
  end
end

app/models/metal.rb
class Metal < ApplicationRecord
  has_many :estimates, inverse_of: :metal

  validates :name, :price_cents, presence: true

  monetize :price_cents

  def full_name
    "#{name} (#{price.format}/mm^2)"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: %i[ show destroy ]

  class EstimateForm
    include ActiveModel::Model

    attr_accessor :file, :metal_id

    delegate :original_filename, to: :file

    def self.model_name
      Estimate.model_name
    end

    def save
      return false unless valid?

      persist
      true
    end

    private

    def content
      @content ||= file.read
    end

    def estimator
      @estimator ||= DxfEstimator.new(content: content)
    end

    def persist
      Estimate.create!(metal_id: metal_id, file: content, name: original_filename, length: estimator.length, width: estimator.width, height: estimator.height, units: estimator.units)
    end
  end

  # GET /estimates
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  def show
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # POST /estimates
  def create
    @estimate = EstimateForm.new(file: estimate_params[:file], metal_id: estimate_params[:metal_id])

    if @estimate.save
      redirect_to @estimate, notice: "Estimate was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /estimates/1
  def destroy
    @estimate.destroy
    redirect_to estimates_url, notice: "Estimate was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estimate_params
      params.require(:estimate).permit(:file, :metal_id)
    end
end

app/controllers/metals_controller.rb
class MetalsController < ApplicationController
  before_action :set_metal, only: %i[ show edit update destroy ]

  # GET /metals
  def index
    @metals = Metal.all
  end

  # GET /metals/1
  def show
  end

  # GET /metals/new
  def new
    @metal = Metal.new
  end

  # GET /metals/1/edit
  def edit
  end

  # POST /metals
  def create
    @metal = Metal.new(metal_params)

    if @metal.save
      redirect_to @metal, notice: "Metal was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /metals/1
  def update
    if @metal.update(metal_params)
      redirect_to @metal, notice: "Metal was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /metals/1
  def destroy
    @metal.destroy
    redirect_to metals_url, notice: "Metal was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metal
      @metal = Metal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def metal_params
      params.require(:metal).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_estimate.html.erb
<div id="<%= dom_id estimate %>">
  <h2 class="my-5 text-lg font-medium mb-1"><%= estimate.name %></h2>

  <p class="my-5">
    <div>
      <strong class="font-medium mb-1">Cut length:</strong>
      <%= estimate.length.round(1) %> <%= estimate.units %>
    </div>
    <div>
      <strong class="font-medium mb-1">Cut time:</strong>
      <%= distance_of_time_in_words(estimate.cut_time) %>
    </div>
    <div>
      <strong class="font-medium mb-1">Cut price:</strong>
      <%= estimate.cut_price.format %>
    </div>
  </p>

  <p class="my-5">
    <div>
      <strong class="font-medium mb-1">Dimensions:</strong>
      <%= estimate.width %> x <%= estimate.height %> <%= estimate.units %>
    </div>
    <div>
      <strong class="font-medium mb-1">Metal price:</strong>
      <%= estimate.metal_price.format %> (<%= estimate.metal.name %>)
    </div>
  </p>

  <p class="my-5">
    <div>
      <strong class="font-medium mb-1">Total price:</strong>
      <%= estimate.total_price.format %>
    </div>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this estimate", estimate, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/estimates/_form.html.erb
<%= form_with(model: estimate, class: "contents") do |form| %>
  <% if estimate.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
        <% estimate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <div data-controller="dropzone dxf" class="relative overflow-hidden mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
      <div class="text-center">
        <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
        </svg>
        <div class="mt-4 flex text-sm leading-6 text-gray-600">
          <%= form.label :file, class: "relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500" do %>
            <span>Upload a file</span>
            <%= form.file_field :file, required: true, class: "sr-only", data: {action: "change->dxf#change"} %>
          <% end %>
          <p class="pl-1">or drag and drop</p>
        </div>
        <p class="text-xs leading-5 text-gray-600">Only DXF is supported</p>
      </div>
      <div class="absolute inset-0 hidden bg-white" data-dxf-target="output"></div>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :metal_id %>
    <%= form.collection_select :metal_id, Metal.all, :id, :full_name, {}, {required: true, class: "mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6"} %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/estimates/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Estimates</h1>
    <%= link_to 'New estimate', new_estimate_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="estimates" class="min-w-full">
    <%= render @estimates %>
  </div>
</div>

app/views/estimates/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New estimate</h1>

  <%= render "form", estimate: @estimate %>

  <%= link_to 'Back to estimates', estimates_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/estimates/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @estimate %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this estimate', estimate_path(@estimate), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to estimates', estimates_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estimator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/metals/_form.html.erb
<%= form_with(model: metal, class: "contents") do |form| %>
  <% if metal.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(metal.errors.count, "error") %> prohibited this metal from being saved:</h2>

      <ul>
        <% metal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/metals/_metal.html.erb
<div id="<%= dom_id metal %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= metal.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= metal.price.format %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this metal", metal, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this metal', edit_metal_path(metal), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/metals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing metal</h1>

  <%= render "form", metal: @metal %>

  <%= link_to "Show this metal", @metal, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to metals", metals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/metals/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Metals</h1>
    <%= link_to 'New metal', new_metal_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="metals" class="min-w-full">
    <%= render @metals %>
  </div>
</div>

app/views/metals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New metal</h1>

  <%= render "form", metal: @metal %>

  <%= link_to 'Back to metals', metals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/metals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @metal %>

    <%= link_to 'Edit this metal', edit_metal_path(@metal), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this metal', metal_path(@metal), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to metals', metals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>